name: Debug Trigger

on:
  push:
    branches:
      - master
    paths:
      - '_posts/**'

jobs:
  test-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: The trigger worked!
        run: echo "I was successfully triggered by a change in the _posts folder."