# .github/workflows/google-indexing.yml
name: Notify Google of New Posts

on:
  push:
    branches:
      - master
    paths:
      - 'blog/_posts/**'

jobs:
  index-posts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetches all history for a reliable diff

      - name: Find new and modified posts
        id: find_files
        run: |
          echo "Finding changed files..."
          files=$(git diff --name-only HEAD^ HEAD | grep 'blog/_posts/' | xargs)
          if [ -z "$files" ]; then
            echo "No new or modified blog posts found."
            echo "files=" >> $GITHUB_OUTPUT
          else
            echo "Found files: $files"
            echo "files=$files" >> $GITHUB_OUTPUT
          fi

      - name: Convert file paths to URLs (Customized for eregis.github.io)
        id: to_urls
        if: steps.find_files.outputs.files
        run: |
          SITE_URL="https://eregis.github.io"
          URLS=""
          
          for file in ${{ steps.find_files.outputs.files }}; do
            # My previous typo is now corrected in this line
            slug=$(echo "$file" | sed -E 's|blog/_posts/([0-9]{4})-([0-9]{2})-([0-9]{2})-(.*)\.md|/blog/\1/\2/\3/\4.html|')
            url="$SITE_URL$slug"
            URLS="$URLS $url"
          done

          echo "Formatted URLs: $URLS"
          echo "urls_list=$(echo $URLS | xargs)" >> $GITHUB_OUTPUT

      - name: Submit URLs to Google Indexing API
        if: steps.to_urls.outputs.urls_list
        # Using a new, alternative action to solve the resolution error
        uses: go-search-console/google-indexing-api-action@v0.2.0
        with:
          # Note: The secret name is the same, but the input variable is different for this action
          service_account_json: ${{ secrets.GCP_SA_KEY }}
          urls: ${{ steps.to_urls.outputs.urls_list }}